### ISSUE TITLE
Cannot import meta from flowdas

### ISSUE THREAD

**Issue by namnt1208** [portu-sim/sd-webui-bmab#11]
Hi, i tried to install bmab, but this is what happen:

Traceback (most recent call last):
  File "D:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-bmab\install.py", line 2, in <module>
    import launch
  File "c:\users\admin\downloads\launch-0.1.3\launch\__init__.py", line 9, in <module>
    from .cli import *
  File "c:\users\admin\downloads\launch-0.1.3\launch\cli.py", line 12, in <module>
    from .app import App
  File "c:\users\admin\downloads\launch-0.1.3\launch\app.py", line 11, in <module>
    from flowdas import meta
ImportError: cannot import name 'meta' from 'flowdas' (C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\flowdas\__init__.py)

When i run install.py

How can i fix it ?

**Comment by portu-sim** [comment]
Do not run install.py outside of stable-diffusion-webui.
stable-diffusion-webui execute install.py in launching application.
Install sd-webui-bmab in stable-diffusion-webui extension tab.
