### ISSUE TITLE
Noise Error

### ISSUE THREAD

**Issue by Yui007** [portu-sim/sd-webui-bmab#24]
hi. i want to use the noise option in controlnet section but it is giving me errors like these :

*** Error running process: /kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/kaggle/working/stable-diffusion-webui/modules/scripts.py", line 718, in process
        script.process(p, *script_args)
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1143, in process
        self.controlnet_hack(p)
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1128, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 969, in controlnet_main_entry
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in input_images]))
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 969, in <listcomp>
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in input_images]))
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 936, in preprocess_input_image
        detected_map, is_image = self.preprocessor[unit.module](
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 80, in decorated_func
        return cached_func(*args, **kwargs)
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 64, in cached_func
        return func(*args, **kwargs)
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 37, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 418, in lineart_standard
        img, remove_pad = resize_image_with_pad(img, res)
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 45, in resize_image_with_pad
        img = cv2.resize(img, (W_target, H_target), interpolation=interpolation)
    cv2.error: OpenCV(4.9.0) /io/opencv/modules/imgproc/src/resize.cpp:4155: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
    

                                                                                                      OR
Like THIS :

*** Error running process: /kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/kaggle/working/stable-diffusion-webui/modules/scripts.py", line 718, in process
        script.process(p, *script_args)
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1143, in process
        self.controlnet_hack(p)
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1128, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 894, in controlnet_main_entry
        model_net, control_model_type = Script.load_control_model(p, unet, unit.model)
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 367, in load_control_model
        control_model = Script.build_control_model(p, unet, model)
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 385, in build_control_model
        raise RuntimeError(f"model not found: {model}")
    RuntimeError: model not found: None

Can you tell me how to fix this or how to use the noise option maybe i am doing something wrong?

**Comment by portu-sim** [comment]
In stable diffusion webui, Settings > BMAB

you can find setting for "ControlNet lineart model"

<img width="361" alt="image" src="https://github.com/portu-sim/sd-webui-bmab/assets/141602933/51325006-09ba-4d36-b43e-43edb338c97f">

You can download that file, put the file into stable-diffusion-webui/extensions/sd-webui-controlnet/models
AND restart webui and reload web.

**Comment by portu-sim** [comment]
<img width="880" alt="image" src="https://github.com/portu-sim/sd-webui-bmab/assets/141602933/1af2aac6-b1a1-41a6-86af-240c20c71c7b">

Set BMAB ControlNet lineart model to YOUR CONTROLNET LINEART MODEL
The model text should be same exactly.
