### ISSUE TITLE
Error loading script: sd_webui_bmab.py on AUTOMATIC1111 1.9.0

### ISSUE THREAD

**Issue by traithanhnam90** [portu-sim/sd-webui-bmab#37]
*** Error loading script: sd_webui_bmab.py
    Traceback (most recent call last):
      File "H:\Stable Difusion\stable-diffusion-webui-1.9.0\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\Stable Difusion\stable-diffusion-webui-1.9.0\modules\script_loading.py", line 14, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\Stable Difusion\stable-diffusion-webui-1.9.0\extensions\sd-webui-bmab\scripts\sd_webui_bmab.py", line 1, in <module>
        from sd_bmab.bmab import BmabExtScript
      File "H:\Stable Difusion\stable-diffusion-webui-1.9.0\extensions\sd-webui-bmab\sd_bmab\bmab.py", line 6, in <module>
        from sd_bmab import parameters
      File "H:\Stable Difusion\stable-diffusion-webui-1.9.0\extensions\sd-webui-bmab\sd_bmab\parameters.py", line 4, in <module>
        from sd_bmab.util import debug_print
      File "H:\Stable Difusion\stable-diffusion-webui-1.9.0\extensions\sd-webui-bmab\sd_bmab\util.py", line 8, in <module>
        from basicsr.utils.download_util import load_file_from_url
    ImportError: cannot import name 'load_file_from_url' from 'basicsr.utils.download_util' (H:\Stable Difusion\stable-diffusion-webui-1.9.0\venv\lib\site-packages\basicsr\utils\download_util.py)

**Comment by portu-sim** [comment]
It's fixed last version of BMAB.

**Comment by traithanhnam90** [comment]
> It's fixed last version of BMAB.

oh, thank you so much, this is my favorite extensions!
Have a good day!
