### ISSUE TITLE
BMAB Preprocessor / Enable Refiner / AttributeError: 'StableDiffusionProcessingTxt2ImgOv' object has no attribute 'sdprocessing'

### ISSUE THREAD

**Issue by RGX650** [portu-sim/sd-webui-bmab#42]
with refiner True True
Noise True True True
Traceback (most recent call last):
  File "C:\AI\SDNEXT\automatic\extensions\sd-webui-bmab-SDNEXT\sd_bmab\pipeline\post\mainpipe.py", line 67, in process
    ret = proc.process(context, processed)
  File "C:\AI\SDNEXT\automatic\extensions\sd-webui-bmab-SDNEXT\sd_bmab\processors\preprocess\refiner.py", line 133, in process
    image = process_img2img_with_controlnet(context, image, options, controlnet)
  File "C:\AI\SDNEXT\automatic\extensions\sd-webui-bmab-SDNEXT\sd_bmab\base\process.py", line 132, in process_img2img_with_controlnet
    i2i_param = build_img2img(context.sdprocessing, image, options)
  File "C:\AI\SDNEXT\automatic\extensions\sd-webui-bmab-SDNEXT\sd_bmab\base\process.py", line 46, in build_img2img
    p = context.sdprocessing
AttributeError: 'StableDiffusionProcessingTxt2ImgOv' object has no attribute 'sdprocessing'
model Ultralytics(face_yolov8n_v2.pt)

**Comment by RGX650** [comment]
I didn't manage to fix it..., is it happening in your main branch too?

**Comment by RGX650** [comment]
?

**Comment by traithanhnam90** [comment]
I'm also having this error!
