### ISSUE TITLE
AttributeError: 'StableDiffusionProcessingTxt2ImgOv' object has no attribute 'sdprocessing'

### ISSUE THREAD

**Issue by traithanhnam90** [portu-sim/sd-webui-bmab#43]
Traceback (most recent call last):
  File "H:\Stable Difusion\stable-diffusion-webui-1.9.0\extensions\sd-webui-bmab\sd_bmab\pipeline\post\mainpipe.py", line 69, in process
    ret = proc.process(context, processed)
  File "H:\Stable Difusion\stable-diffusion-webui-1.9.0\extensions\sd-webui-bmab\sd_bmab\processors\postprocess\inpaintlama.py", line 132, in process
    i2i_param = build_img2img(context.sdprocessing, image, opt)
  File "H:\Stable Difusion\stable-diffusion-webui-1.9.0\extensions\sd-webui-bmab\sd_bmab\base\process.py", line 45, in build_img2img
    p = context.sdprocessing
AttributeError: 'StableDiffusionProcessingTxt2ImgOv' object has no attribute 'sdprocessing'
Unknown model:

Sorry, I need help, I got the above error when using A1111 1.9.0

**Comment by portu-sim** [comment]
It's fixed. Thank you for your reporting.
