### ISSUE TITLE
UI is broken 

### ISSUE THREAD

**Issue by cl4usman** [portu-sim/sd-webui-bmab#45]
version: [1.9.3] (https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/1c0a0c4c26f78c32095ebc7f8af82f5c04fca8c0) •  python: 3.10.12  • 
 torch: 2.1.2+cu121  • 
 xformers: 0.0.23.post1  • 
 gradio: 3.41.2  • 
 checkpoint: [117d831558](https://google.com/search?q=117d831558a7ffaa55c30c04a38cbe0e89423d84d12d23910435c1d1c693fd14)

**Comment by portu-sim** [comment]
Is there any capture?

**Comment by skyliwq** [comment]
To create a public link, set share=True in launch().
2024-09-04 00:01:41 Traceback (most recent call last):
2024-09-04 00:01:41 File "/app/stable-diffusion-webui/launch.py", line 48, in
2024-09-04 00:01:41 main()
2024-09-04 00:01:41 File "/app/stable-diffusion-webui/launch.py", line 44, in main
2024-09-04 00:01:41 start()
2024-09-04 00:01:41 File "/app/stable-diffusion-webui/modules/launch_utils.py", line 469, in start
2024-09-04 00:01:41 webui.webui()
2024-09-04 00:01:41 File "/app/stable-diffusion-webui/webui.py", line 112, in webui
2024-09-04 00:01:41 create_api(app)
2024-09-04 00:01:41 File "/app/stable-diffusion-webui/webui.py", line 22, in create_api
2024-09-04 00:01:41 api = Api(app, queue_lock)
2024-09-04 00:01:41 ^^^^^^^^^^^^^^^^^^^^
2024-09-04 00:01:41 File "/app/stable-diffusion-webui/modules/api/api.py", line 265, in init
2024-09-04 00:01:41 self.default_script_arg_txt2img = self.init_default_script_args(txt2img_script_runner)
2024-09-04 00:01:41 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-04 00:01:41 File "/app/stable-diffusion-webui/modules/api/api.py", line 328, in init_default_script_args
2024-09-04 00:01:41 if script.ui(script.is_img2img):
2024-09-04 00:01:41 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-04 00:01:41 File "/app/stable-diffusion-webui/extensions/sd-webui-bmab/sd_bmab/bmab.py", line 48, in ui
2024-09-04 00:01:41 return ui.create_ui(self, is_img2img)
2024-09-04 00:01:41 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-04 00:01:41 File "/app/stable-diffusion-webui/extensions/sd-webui-bmab/sd_bmab/ui.py", line 553, in create_ui
2024-09-04 00:01:41 elem += gr.Dropdown(label='Watermark Font', visible=True, value=fonts[0], choices=fonts)
2024-09-04 00:01:41 ~~~~~^^^
2024-09-04 00:01:41 IndexError: list index out of range

**Comment by portu-sim** [comment]
There is no font available.
It's fixed.
