### ISSUE TITLE
BMAB>controlnet>enable noise error

### ISSUE THREAD

**Issue by jackytop** [portu-sim/sd-webui-bmab#47]
I get this error when I activate BMAB>controlnet>enable noise

> 2024-05-17 01:02:15,019 - ControlNet - INFO - unit_separate = False, style_align = False 55/55 [00:06<00:00, 11.79it/s]
*** Error running process: D:\sd\webui_latest_test\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\sd\webui_latest_test\modules\scripts.py", line 825, in process
        script.process(p, *script_args)
      File "D:\sd\webui_latest_test\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1215, in process
        self.controlnet_hack(p)
      File "D:\sd\webui_latest_test\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1200, in controlnet_hack        self.controlnet_main_entry(p)
      File "D:\sd\webui_latest_test\extensions\sd-webui-controlnet\scripts\controlnet.py", line 912, in controlnet_main_entry
        model_net, control_model_type = Script.load_control_model(p, unet, unit.model)
      File "D:\sd\webui_latest_test\extensions\sd-webui-controlnet\scripts\controlnet.py", line 430, in load_control_model
        control_model = Script.build_control_model(p, unet, model)
      File "D:\sd\webui_latest_test\extensions\sd-webui-controlnet\scripts\controlnet.py", line 448, in build_control_model
        raise RuntimeError(f"model not found: {model}")
    RuntimeError: model not found: None

---
any clue to fix this problem?

**Comment by portu-sim** [comment]
You should download controlnet model from huggingface.co.
BMAB Noise Function requires ControlNet model "lineart", control_v11p_sd15_lineart_fp16.safetensors.
You can download from internent and put it into "**### extensions/sd-webui-controlnet/models**", not BMAB.
Please check SD-WEB-UI -> Settings -> BMAB. You can see ControlNet Model List that BMAB requires.

**Comment by jackytop** [comment]
> You should download controlnet model from huggingface.co. BMAB Noise Function requires ControlNet model "lineart", control_v11p_sd15_lineart_fp16.safetensors. You can download from internent and put it into "**extensions/sd-webui-controlnet/models**", not BMAB. Please check SD-WEB-UI -> Settings -> BMAB. You can see ControlNet Model List that BMAB requires.

Thank you so much! The Issue's gone now and all good!
Great support sir!
