### ISSUE TITLE
ValueError: Coordinate 'right' is less than 'left'

### ISSUE THREAD

**Issue by Kimthanh27** [portu-sim/sd-webui-bmab#48]
*** Error running process: D:\FORGE\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\FORGE\webui\modules\scripts.py", line 803, in process
        script.process(p, *script_args)
      File "D:\FORGE\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\FORGE\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 548, in process
        self.process_unit_after_click_generate(p, unit, params, *args, **kwargs)
      File "D:\FORGE\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\FORGE\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 298, in process_unit_after_click_generate
        input_list, resize_mode = self.get_input_data(p, unit, preprocessor, h, w)
      File "D:\FORGE\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 227, in get_input_data
        image = self.try_crop_image_with_a1111_mask(p, unit, image, resize_mode, preprocessor)
      File "D:\FORGE\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 143, in try_crop_image_with_a1111_mask
        input_image = [x.crop(crop_region) for x in input_image]
      File "D:\FORGE\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 143, in <listcomp>
        input_image = [x.crop(crop_region) for x in input_image]
      File "D:\FORGE\system\python\lib\site-packages\PIL\Image.py", line 1224, in crop
        raise ValueError(msg)
    ValueError: Coordinate 'right' is less than 'left'
It seems that the Mbab is conflicting with the ControlNet extension. I have downloaded the Control Depth Hand model and am using Mbab Face and Hand (depth hand refiner) , but I keep encountering errors. Could you please provide guidance on how to resolve this issue? Thank you very much.

**Comment by portu-sim** [comment]
bmab not support forge.
