### ISSUE TITLE
will you make this support for sd webui forge?

### ISSUE THREAD

**Issue by jasoncow007** [portu-sim/sd-webui-bmab#51]
*** Error running postprocess_image: D:\sd-webui_forge\webui\extensions\sd-webui-bmab\scripts\sd_webui_bmab.py
    Traceback (most recent call last):
      File "D:\sd-webui_forge\webui\modules\scripts.py", line 940, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\sd-webui_forge\webui\extensions\sd-webui-bmab\sd_bmab\bmab.py", line 83, in postprocess_image
        with controlnet.PreventControlNet(p.context, cn_enabled=post.is_controlnet_required(p.context)):
      File "D:\sd-webui_forge\webui\extensions\sd-webui-bmab\sd_bmab\controlnet.py", line 101, in __enter__
        model = self.p.sd_model.model.diffusion_model
    AttributeError: 'StableDiffusion' object has no attribute 'model'

**Comment by portu-sim** [comment]
bmab not support forge.
