### ISSUE TITLE
    AttributeError: 'Options' object has no attribute 'bmab_for_developer'

### ISSUE THREAD

**Issue by xianrenzhang007** [portu-sim/sd-webui-bmab#6]
*** Error calling: J:\sd-webui-aki-v4.3\extensions\sd-webui-bmab\scripts\sd_webui_bmab.py/ui
    Traceback (most recent call last):
      File "J:\sd-webui-aki-v4.3\modules\scripts.py", line 402, in wrap_call
        return func(*args, **kwargs)
      File "J:\sd-webui-aki-v4.3\extensions\sd-webui-bmab\sd_bmab\bmab.py", line 112, in ui
        return self._create_ui(is_img2img)
      File "J:\sd-webui-aki-v4.3\extensions\sd-webui-bmab\sd_bmab\bmab.py", line 563, in _create_ui
        with gr.Accordion(f'BMAB Testroom', open=False, visible=shared.opts.bmab_for_developer):
      File "J:\sd-webui-aki-v4.3\modules\options.py", line 117, in __getattr__
        return super(Options, self).__getattribute__(item)
    AttributeError: 'Options' object has no attribute 'bmab_for_developer'

An error occurred after updating

**Comment by portu-sim** [comment]
It's fixed. Please update BMAB.

**Comment by xianrenzhang007** [comment]
ok

> 它是固定的。请更新 BMAB。
